spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qweasd789
    url: jdbc:mysql://127.0.0.1:3306/dbsell
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell

wechat:
  mpAppId: wx742019518dea57a4
  mpAppSecret: wx742019518dea57a4
  mchId: 123456
  mchkey: dhfjjkahdfjk
  keyPath: /var/weixin_cert/h5.p12

